### PR TITLE
Port c++ tests

### PR DESCRIPTION
**Pull request by RadicalZephyr**
Start on porting [all of the tests from sodium-cxx-alt](/clinuxrulz/sodium-cxx-alt/blob/master/tests/test_sodium.cpp).

To make sure I don't miss any I'm also rearranging the tests so they are in the same order in the file.

### CODE REVIEW

**Comment by clinuxrulz** [comment]
That's awesome. If I get time tomorrow, I'll apply the same fixes done in the C++ version to get those tests to pass in the Rust version.

Don't worry about any move semantic tests. C++ is a different beast when it comes to moves.

**Comment by clinuxrulz** [comment]
OK. I've done the necessary changes for those tests to pass (modelled from the C++ version). But there should be a couple more failing tests involving lazyness with ```switchC``` / ```switchS```. I can't remember which tests they are in the C++ version, I'll have a dig later.

If your gonna add more tests, do a pull from the master branch first.

**Comment by RadicalZephyr** [comment]
Sounds good! I probably won't get to adding more tests until the weekend but I'll make sure I'm up to date before I do.

**Comment by clinuxrulz** [comment]
I believe it is this one for reference:

https://github.com/clinuxrulz/sodium-cxx-alt/blob/0340705260f9a1bb26706a06eaa1abb3ecc68950/tests/test_sodium.cpp#L884

Which may already pass (not sure). Because I have a "before end of transaction" Vec added which is used to call update() on Nodes for initial state after any looping (CellLoop/StreamLoop) is done. But better to be safe than sorry.

**Comment by clinuxrulz** [comment]
I can translate that last test if you like. It will cover the remaining bugs I've noticed in the C++ version that I expect to also be in the Rust version.

Writing tests is a bit of a full tedious task. At least for me.

If you feel like something to do in this code base, feel free to have a crack at the milestone tasks. They should be a little less boring to do.

**Pull request merged**
